global:
  scrape_interval: 10s

  scrape_timeout: 10s

  evaluation_interval: 15s

  external_labels:
    monitor: 'my-app'

rule_files:
  - 'alert.rules'

alerting:
  alertmanagers:
      - static_configs:
        - targets:
          - 'alert-manager:9093'

scrape_configs:
  # Can be declared multiple job
  - job_name: 'monitoring-app'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 15s
    static_configs:
      - targets: [ 'app:8081' ]

  - job_name: 'monitoring-container'
    scrape_interval: 10s
    static_configs:
      - targets: [ 'cadvisor:8080' ]

